import { Occupation } from './d3/TimeLine';

export const occupationData: Array<Occupation> = [
  {
    id: '001',
    selected: true,
    title: 'Data Visualization Intern',
    category: 'Work',
    tag: ['coder'],
    start: new Date('2020-01-03'),
    end: new Date('2020-07-11'),
  },
  {
    id: '002',
    selected: true,
    title: 'Gardener',
    category: 'Work',
    tag: ['coder'],
    start: new Date('2019-03-01'),
    end: new Date('2019-10-31'),
  },
  {
    id: '003',
    selected: true,
    title: 'Intensive German (A1-B1)',
    category: 'Education',
    tag: ['coder'],
    start: new Date('2019-01-01'),
    end: new Date('2019-04-03'),
  },
  {
    id: '004',
    selected: true,
    title: 'Design Consultant',
    category: 'Volunteer',
    tag: ['coder'],
    start: new Date('2016-10-01'),
    end: new Date('2018-01-03'),
  },
  {
    id: '005',
    selected: true,
    title: 'Fellowship Programme',
    category: 'Education',
    tag: ['coder'],
    start: new Date('2016-10-01'),
    end: new Date('2017-10-01'),
  },
  {
    id: '006',
    selected: true,
    title: 'Regenerative Garden Designer',
    category: 'Work',
    tag: ['coder'],
    start: new Date('2016-04-01'),
    end: new Date('2018-10-01'),
  },
  {
    id: '007',
    selected: true,
    title: 'Senior Landscaper',
    category: 'Work',
    tag: ['coder'],
    start: new Date('2015-08-01'),
    end: new Date('2016-02-01'),
  },
  {
    id: '008',
    selected: true,
    title: 'Farm Manager',
    category: 'Volunteer',
    tag: ['coder'],
    start: new Date('2015-02-01'),
    end: new Date('2015-07-15'),
  },
  {
    id: '010',
    selected: true,
    title: 'WWOOFer Volunteer',
    category: 'Volunteer',
    tag: ['coder'],
    start: new Date('2014-10-01'),
    end: new Date('2015-01-01'),
  },
  {
    id: '012',
    selected: true,
    title: 'Permaculture Design Certificate',
    category: 'Education',
    tag: ['coder'],
    start: new Date('2014-02-01'),
    end: new Date('2015-06-01'),
  },
  {
    id: '013',
    selected: true,
    title: 'System Analyst',
    category: 'Work',
    tag: ['coder'],
    start: new Date('2013-06-01'),
    end: new Date('2013-12-21'),
  },
  {
    id: '014',
    selected: true,
    title: 'Orientation Coodinator',
    category: 'Volunteer',
    tag: ['coder'],
    start: new Date('2013-01-01'),
    end: new Date('2013-09-15'),
  },
  {
    id: '015',
    selected: true,
    title: 'MArch Foundation',
    category: 'Education',
    tag: ['coder'],
    start: new Date('2012-09-01'),
    end: new Date('2013-04-21'),
  },
  {
    id: '016',
    selected: true,
    title: 'Baker',
    category: 'Work',
    tag: ['coder'],
    start: new Date('2011-10-01'),
    end: new Date('2012-04-21'),
  },
  {
    id: '017',
    selected: true,
    title: 'Bachelor of Arts',
    category: 'Education',
    tag: ['coder'],
    start: new Date('2006-09-01'),
    end: new Date('2010-04-21'),
  },
];
