import { Occupation, LifeEvent } from './d3/TimeLine';

export const occupationData: Array<Occupation> = [
  {
    id: '001',
    selected: true,
    title: 'Data Visualization Intern',
    company: 'Interactive Things',
    location: 'Switzerland',
    description:
      'Involved across the process of digital content creation. Working with designers on ideation, prototyping and client coordination as well as assisting developers with implementation from cleaning data, building web app features, and continuous integration and deployment.',
    skills: [
      'Web Design(HTML, CSS)',
      'Frontend(Typescript, React)',
      'Data Analysis (R, Tableau)',
      'Data Visualization (D3.js)',
    ],
    character: [
      'Multidisciplinary Teamplayer',
      'Sellf Motivated',
      'Problem Solver',
    ],
    category: 'Work',
    tag: ['coder'],
    start: new Date('2020-01-03'),
    end: new Date('2020-07-11'),
  },
  {
    id: '002',
    selected: true,
    title: 'Gardener',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Work',
    tag: ['coder'],
    start: new Date('2019-03-01'),
    end: new Date('2019-10-31'),
  },
  {
    id: '003',
    selected: true,
    title: 'Intensive German (A1-B1)',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Education',
    tag: ['coder'],
    start: new Date('2019-01-01'),
    end: new Date('2019-04-03'),
  },
  {
    id: '004',
    selected: true,
    title: 'Design Consultant',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Volunteer',
    tag: ['coder'],
    start: new Date('2016-11-01'),
    end: new Date('2018-12-21'),
  },
  {
    id: '005',
    selected: true,
    title: 'Fellowship Programme',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Education',
    tag: ['coder'],
    start: new Date('2016-10-01'),
    end: new Date('2017-10-01'),
  },
  {
    id: '006',
    selected: true,
    title: 'Regenerative Garden Designer',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Work',
    tag: ['coder'],
    start: new Date('2016-04-01'),
    end: new Date('2018-10-01'),
  },
  {
    id: '007',
    selected: true,
    title: 'Senior Landscaper',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Work',
    tag: ['coder'],
    start: new Date('2015-08-01'),
    end: new Date('2016-02-01'),
  },
  {
    id: '008',
    selected: true,
    title: 'Farm Manager',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Volunteer',
    tag: ['coder'],
    start: new Date('2015-02-01'),
    end: new Date('2015-07-15'),
  },
  {
    id: '010',
    selected: true,
    title: 'WWOOFer Volunteer',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Volunteer',
    tag: ['coder'],
    start: new Date('2014-10-01'),
    end: new Date('2015-01-01'),
  },
  {
    id: '012',
    selected: true,
    title: 'Permaculture Design Certificate',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Education',
    tag: ['coder'],
    start: new Date('2014-02-01'),
    end: new Date('2015-06-01'),
  },
  {
    id: '013',
    selected: true,
    title: 'System Analyst',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Work',
    tag: ['coder'],
    start: new Date('2013-06-01'),
    end: new Date('2013-12-21'),
  },
  {
    id: '014',
    selected: true,
    title: 'Orientation Coodinator',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Volunteer',
    tag: ['coder'],
    start: new Date('2013-01-01'),
    end: new Date('2013-09-15'),
  },
  {
    id: '015',
    selected: true,
    title: 'MArch Foundation',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Education',
    tag: ['coder'],
    start: new Date('2012-09-01'),
    end: new Date('2013-04-21'),
  },
  {
    id: '016',
    selected: true,
    title: 'Baker',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Work',
    tag: ['coder'],
    start: new Date('2012-01-01'),
    end: new Date('2012-06-21'),
  },
  {
    id: '017',
    selected: true,
    title: 'Baker',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Work',
    tag: ['coder'],
    start: new Date('2011-06-01'),
    end: new Date('2011-12-21'),
  },
  {
    id: '018',
    selected: true,
    title: 'Bachelor of Arts',
    company: '',
    location: '',
    description: '',
    skills: [''],
    character: [''],
    category: 'Education',
    tag: ['coder'],
    start: new Date('2006-09-01'),
    end: new Date('2011-04-21'),
  },
];

export const lifeEventData: Array<LifeEvent> = [
  { id: '001', date: new Date('2020-01-03'), title: 'Moved to Switzerland' },
  { id: '002', date: new Date('2019-01-03'), title: 'Moved to Germany' },
  { id: '003', date: new Date('2015-08-03'), title: 'Moved to UK' },
  { id: '004', date: new Date('2014-08-01'), title: 'Moved to Spain' },
  {
    id: '005',
    date: new Date('2014-01-01'),
    title: 'Traveled Central America',
  },
  {
    id: '005',
    date: new Date('2012-08-01'),
    title: 'Started MArch',
  },
];
