name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    env:
      DB_FILE_NAME: database/db.sqlite
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile
      - run: bun lint

  verify-types:
    name: "Types"
    runs-on: ubuntu-latest
    env:
      DB_FILE_NAME: database/db.sqlite
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile
      - run: bun typecheck
